/**
 * tests/cs44-docs-impl-alignment.test.mjs — CS44 deliverable D44-4.
 *
 * Doc-drift watchdog for the Copilot-engagement GraphQL fragment.
 *
 * Background: CS41 R5 surfaced that OPERATIONS.md (and CHANGELOG.md) described
 * the Copilot Bot identity-resolution path as `node(login:) / ... on Bot`, but
 * the actual implementation in lib/copilot-engage.mjs uses
 * `node(id: $id) { ... on Bot { databaseId login } }` with the hardcoded
 * Copilot Bot node ID `BOT_kgDOCnlnWA` (per LRN-009 + ADR-0004 § ADR4-2,
 * because `user(login: 'copilot-pull-request-reviewer')` returns null).
 *
 * CS44 corrected the documentation in three places:
 *   - template/composed/OPERATIONS.md (the composed-mirror source)
 *   - OPERATIONS.md (regenerated by `harness sync`)
 *   - CHANGELOG.md (the [0.5.0] CS41 row + a CS44 [Unreleased] / Changed bullet)
 *
 * This test pins all FOUR touchpoints (lib + composed/OPERATIONS + root
 * OPERATIONS + CHANGELOG) so that any future edit which silently re-introduces
 * the old `node(login:)` wording — or removes the canonical literals — trips a
 * hard test failure. Future updates to the GraphQL fragment shape MUST be
 * coordinated across all four files in a single PR.
 *
 * Per Decisions C44-4 / C44-7.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

const TOUCHPOINTS = [
  { id: 'lib', relPath: 'lib/copilot-engage.mjs' },
  { id: 'composed-operations', relPath: 'template/composed/OPERATIONS.md' },
  { id: 'root-operations', relPath: 'OPERATIONS.md' },
  { id: 'changelog', relPath: 'CHANGELOG.md' },
];

function read(relPath) {
  return readFileSync(path.join(REPO_ROOT, relPath), 'utf8');
}

describe('CS44 — Copilot-engage docs/impl alignment watchdog', () => {
  for (const tp of TOUCHPOINTS) {
    it(`${tp.id} (${tp.relPath}) mentions the canonical node(id: ...) GraphQL fragment`, () => {
      const content = read(tp.relPath);
      assert.match(
        content,
        /node\(id:/,
        `Expected ${tp.relPath} to reference the canonical node(id: ...) GraphQL fragment ` +
        `(actual implementation at lib/copilot-engage.mjs uses node(id: $id) { ... on Bot { databaseId login } }). ` +
        `If you intentionally renamed the fragment, update all four touchpoints in ` +
        `tests/cs44-docs-impl-alignment.test.mjs in the same PR.`,
      );
    });

    it(`${tp.id} (${tp.relPath}) mentions the hardcoded Copilot Bot node ID BOT_kgDOCnlnWA`, () => {
      const content = read(tp.relPath);
      assert.match(
        content,
        /BOT_kgDOCnlnWA/,
        `Expected ${tp.relPath} to reference the hardcoded Copilot Bot node ID BOT_kgDOCnlnWA ` +
        `(per LRN-009 + ADR-0004 § ADR4-2: user(login: 'copilot-pull-request-reviewer') returns null, ` +
        `so the engage CLI hardcodes the Bot node ID). ` +
        `If the Bot node ID has changed upstream, update all four touchpoints in the same PR.`,
      );
    });
  }

  it('the stale `node(login:)` wording is GONE from all four touchpoints', () => {
    for (const tp of TOUCHPOINTS) {
      const content = read(tp.relPath);
      assert.doesNotMatch(
        content,
        /node\(login:\)/,
        tp.relPath + ' still contains the stale node(login:) wording from before CS44. ' +
        'Replace it with the canonical node(id: $id) { ... on Bot { databaseId login } } fragment ' +
        '+ the hardcoded BOT_kgDOCnlnWA node ID.',
      );
    }
  });
});
