#!/usr/bin/env node
/**
 * project/clickstops/active/active_cs11_self-host/placeholder-audit.mjs
 *
 * CS11 Stage A.3: placeholder audit — for each managed + composed file in
 * harness.config.json, render the template via applyTemplating() (lenient
 * mode per D9), then scan the rendered output for any remaining `{{...}}`
 * token. Classify each:
 *   - resolved: should be empty (every {{key}} got substituted)
 *   - intentional-literal: documented prose tokens like {{templating}}
 *   - out-of-scope: false positive from prose discussing template syntax
 *
 * Any unclassified token is a Stage A blocker (expand templating map until clean).
 *
 * Usage: node placeholder-audit.mjs [--out <path>]
 *   Default --out: placeholder-audit.md (in CWD).
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyTemplating } from '../../../../lib/templating.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..', '..');

let outPath = path.join(__dirname, 'placeholder-audit.md');
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '--out') {
    if (!argv[i + 1] || argv[i + 1].startsWith('-')) {
      process.stderr.write('--out requires a value\n');
      process.exit(2);
    }
    outPath = path.resolve(process.cwd(), argv[++i]);
  }
}

const config = JSON.parse(readFileSync(path.join(REPO_ROOT, 'harness.config.json'), 'utf8'));
const templating = config.templating ?? {};

// Documented intentional-literal tokens (prose references to the templating
// system itself, NOT substitution targets).
const INTENTIONAL_LITERALS = new Set([
  'templating',
  'key',
  'X',
  'Y',
  'X.Y',
  'a',
  'b',
  'name',
  'unknown',
  'project.agent_suffix',
  'agent_suffix.upper',
]);

function classify(token, sourceTemplateContent) {
  // Strip whitespace inside braces for normalization
  const inner = token.replace(/^\{\{\s*/, '').replace(/\s*\}\}$/, '');
  // Check if the source template had this token in escaped form (\{{key}})
  // — CS03b's escape syntax consumes the \ and renders {{key}} literally.
  // This is intentional (template author wanted the literal post-render).
  const escapedInTemplate = sourceTemplateContent &&
    sourceTemplateContent.includes('\\' + token);
  if (escapedInTemplate) {
    return { class: 'intentional-literal', detail: `escaped in source template (\\{{${inner}}}) per CS03b escape syntax` };
  }
  if (Object.prototype.hasOwnProperty.call(templating, inner)) {
    return { class: 'should-have-resolved', detail: `key "${inner}" exists in templating map but did not substitute (non-string value? bad template?)` };
  }
  if (INTENTIONAL_LITERALS.has(inner)) {
    return { class: 'intentional-literal', detail: `documented prose token` };
  }
  // Heuristic: tokens with dots are documented out-of-scope examples (LRN-049).
  if (inner.includes('.')) {
    return { class: 'intentional-literal', detail: `dot-notation example token (LRN-049)` };
  }
  return { class: 'unclassified', detail: `not in templating map and not in known-literal list` };
}

const allTargets = [
  ...config.managed.files.map(f => ({ file: f, cls: 'managed' })),
  ...config.composed.files.map(f => ({ file: f, cls: 'composed' })),
];

const findings = [];
let totalTokens = 0;
let totalUnclassified = 0;

for (const { file, cls } of allTargets) {
  const tpl = path.join(REPO_ROOT, 'template', cls, file);
  if (!existsSync(tpl)) continue;
  const tplRaw = readFileSync(tpl, 'utf8').replace(/^\uFEFF/, '');
  const rendered = applyTemplating(tplRaw, templating);
  const matches = [...rendered.matchAll(/\{\{[^{}]*\}\}/g)];
  for (const m of matches) {
    totalTokens++;
    const lineNum = rendered.slice(0, m.index).split('\n').length;
    const c = classify(m[0], tplRaw);
    if (c.class === 'unclassified') totalUnclassified++;
    findings.push({ file, cls, line: lineNum, token: m[0], class: c.class, detail: c.detail });
  }
}

const lines = [];
lines.push('# CS11 placeholder audit');
lines.push('');
lines.push('> Generated by `placeholder-audit.mjs`. Scans every rendered managed + composed file');
lines.push('> for remaining `{{...}}` tokens and classifies each as resolved / intentional-literal /');
lines.push('> unclassified. Lenient templating mode per D9. Any `unclassified` row is a Stage A');
lines.push('> blocker (expand the `templating` map in `harness.config.json` until clean).');
lines.push('');
lines.push('| File | Class | Line | Token | Classification | Detail |');
lines.push('|---|---|---|---|---|---|');
for (const f of findings) {
  lines.push(`| \`${f.file}\` | ${f.cls} | ${f.line} | \`${f.token}\` | **${f.class}** | ${f.detail} |`);
}
lines.push('');
lines.push('---');
lines.push('');
lines.push(`**Summary**: ${totalTokens} unresolved tokens found across ${allTargets.length} rendered files.`);
lines.push(`- ${findings.filter(f => f.class === 'intentional-literal').length} classified as intentional-literal (OK).`);
lines.push(`- ${findings.filter(f => f.class === 'should-have-resolved').length} classified as should-have-resolved (BUG — fix templating map or escape).`);
lines.push(`- ${totalUnclassified} unclassified (BLOCKER — investigate each).`);
lines.push('');

writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
process.stdout.write(`Wrote ${outPath}\n`);
process.stdout.write(`${totalTokens} unresolved tokens; ${totalUnclassified} unclassified\n`);
// Treat `should-have-resolved` AND `unclassified` as failure-worthy. Both
// indicate a problem the orchestrator should investigate before close-out.
const totalProblems = findings.filter(f => f.class === 'should-have-resolved' || f.class === 'unclassified').length;
process.exit(totalProblems > 0 ? 1 : 0);
