#!/usr/bin/env node
/**
 * project/clickstops/active/active_cs11_self-host/render-preview.mjs
 *
 * CS11 Stage A.3: render preview — for each managed + composed file declared
 * in harness.config.json, read the corresponding template, apply templating
 * substitutions, and emit a diff between the current root content and the
 * rendered template. This is the actual reviewer artifact for the manual-write
 * path (D7); `harness sync --dry-run --report` cannot produce a useful
 * per-file preview because composed planning fails before any preview is
 * generated.
 *
 * Usage: node render-preview.mjs [--out <path>]
 *   Default --out: render-preview.md (in CWD).
 */

import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyTemplating } from '../../../../lib/templating.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..', '..');

let outPath = path.join(__dirname, 'render-preview.md');
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '--out') {
    if (!argv[i + 1] || argv[i + 1].startsWith('-')) {
      process.stderr.write('--out requires a value\n');
      process.exit(2);
    }
    outPath = path.resolve(process.cwd(), argv[++i]);
  }
}

const config = JSON.parse(readFileSync(path.join(REPO_ROOT, 'harness.config.json'), 'utf8'));
const templating = config.templating ?? {};

function templatePathFor(rel, cls) {
  return path.join(REPO_ROOT, 'template', cls, rel);
}

function quickDiff(a, b) {
  const aLines = a.split('\n');
  const bLines = b.split('\n');
  const out = [];
  out.push(`current root: ${aLines.length} lines`);
  out.push(`rendered tpl: ${bLines.length} lines`);
  out.push(`identical?:   ${a === b ? 'YES (no migration write needed)' : 'NO (migration write required)'}`);
  if (a === b) return out.join('\n');
  // Simple length sample
  const sampleN = Math.min(5, Math.max(0, bLines.length - aLines.length));
  if (sampleN > 0) {
    out.push(`first ${sampleN} lines that differ (rendered):`);
    for (let i = 0; i < sampleN; i++) out.push(`  + ${bLines[i] ?? ''}`);
  }
  return out.join('\n');
}

const sections = [];
sections.push('# CS11 render preview');
sections.push('');
sections.push('> Generated by `render-preview.mjs`. For each managed + composed file declared in');
sections.push('> `harness.config.json`, this report shows whether the current root content already');
sections.push('> matches the rendered template (no migration write needed) or differs (write required).');
sections.push('> Stage B.1 manually writes any file marked "NO" to root. Stage B.2 byte-match-verifies.');
sections.push('');

const allTargets = [
  ...config.managed.files.map(f => ({ file: f, cls: 'managed' })),
  ...config.composed.files.map(f => ({ file: f, cls: 'composed' })),
];

let writesNeeded = 0;
for (const { file, cls } of allTargets) {
  sections.push(`## ${cls}: \`${file}\``);
  sections.push('');
  const tpl = templatePathFor(file, cls);
  const rootPath = path.join(REPO_ROOT, file);
  if (!existsSync(tpl)) {
    sections.push(`⚠️ Template not found: \`${path.relative(REPO_ROOT, tpl)}\``);
    sections.push('');
    continue;
  }
  const tplRaw = readFileSync(tpl, 'utf8').replace(/^\uFEFF/, '');
  const rendered = applyTemplating(tplRaw, templating);
  const rootContent = existsSync(rootPath)
    ? readFileSync(rootPath, 'utf8').replace(/^\uFEFF/, '')
    : '';
  if (rendered !== rootContent) writesNeeded++;
  sections.push('```');
  sections.push(quickDiff(rootContent, rendered));
  sections.push('```');
  sections.push('');
}

sections.push('---');
sections.push('');
sections.push(`**Summary**: ${writesNeeded} of ${allTargets.length} files require a migration write in Stage B.1.`);
sections.push('');

writeFileSync(outPath, sections.join('\n') + '\n', 'utf8');
process.stdout.write(`Wrote ${outPath}\n`);
process.stdout.write(`${writesNeeded}/${allTargets.length} files require migration write\n`);
